### ISSUE TITLE
Cpu Fuel is subtracted with overflow.

### ISSUE THREAD

**Issue by rbran** [icicle-emu/icicle-emu#5] opened 2023-03-24 13:43 UTC
https://github.com/icicle-emu/icicle-emu/blob/6184b3221754e2ea591e99e6ad86f097ecf9253b/icicle-vm/src/lib.rs#L503

Will result in a `attempt to subtract with overflow` if a `Vm::step` is called with the number steps being the exact size of the block.

Eg:

```asm
.text
mov r0, #1
mov r1, #2
```
Will error if called with `vm.step(2)`.

**Comment by mchesser** [comment] 2023-03-26 23:43
Thanks for the report. However, I wasn't able to reproduce this.

I compiled the following binary:

```asm
BITS 64
global _start
section .text
_start:
    mov rax, 1
    mov rbx, 1
```

Using:

```
nasm test.asm -f elf64 -o test.o
ld.lld.exe -o test.elf test.o
```

Then ran:

```rust
fn main() {
    let cpu_config = icicle_vm::cpu::Config::from_target_triple("x86_64-none");
    let mut vm = icicle_vm::build(&cpu_config).unwrap();
    // Force the lifter to generate a block with two instructions.
    vm.lifter.settings.max_instructions_per_block = 2;

    let mut env = icicle_vm::env::build_auto(&mut vm).unwrap();
    env.load(&mut vm.cpu, b"./test.elf").unwrap();
    vm.env = env;

    let exit = vm.step(2);
    println!("{}", icicle_vm::debug::current_disasm(&mut vm));
    println!("{exit:?}");
}
```

I think there is probably something else going on. Normally, if `executed_instructions` would be greater than `fuel.remaining`, then we should exit with `block.offset == 0` because of the check injected by the JIT: https://github.com/icicle-emu/icicle-emu/blob/master/icicle-jit/src/translate/mod.rs#L861 which should prevent the code from being run because of the condition here: https://github.com/icicle-emu/icicle-emu/blob/6184b3221754e2ea591e99e6ad86f097ecf9253b/icicle-vm/src/lib.rs#L484

One guess for what could be happening is that some invalidation logic has gone wrong and the JIT block is out-of-sync with the actual block causing a mismatch in the count.

If you can provide some additional details to help track this down, that would be useful.

**Comment by rbran** [comment] 2023-03-27 13:01
Sorry, this seems to only happen on ARM, here how I reproduced that: https://github.com/rbran/popsicle/tree/cpu-fuel-overflow

I'm unable to give you better answer here because I only know what the code does, not what is suppose to do.

Here what I found out with some basic debugging:

- My code call `Vm::step`.
- `Vm::step` call `Vm::run`
- The loop in `Vm::run` is executed twice
- On the second call to `Vm::run_block_jit`, the  start with 2 and `block_offset` 0
- The call `jit_func` run the 2 assembly instructions, and modify the `fuel.remaining` to 0 and `block_offset` to 5
- The call `Vm::jit_exit_before_end_of_block` subtract with overflow because `executed_instructions` is 2 and `fuel.remaining` is 0

**Comment by rbran** [comment] 2023-03-27 13:17
Here my output with some extra prints added to the icicle-vm code:
```
before jit_func: fuel_remaining 2, block_offset 0
0x008000: Some("mov r0,#0x1")
r0 0x000000  r1 0x000000  pc 0x008000

0x008000: Some("mov r0,#0x1")
r0 0x000001  r1 0x000000  pc 0x008000

after jit_func: fuel_remaining 0, block_offset 5, exception.code InvalidInstruction 4097
[/home/rbran/src/icicle-emu/icicle-vm/src/lib.rs:574] self.cpu.fuel.remaining = 0
[/home/rbran/src/icicle-emu/icicle-vm/src/lib.rs:575] executed_instructions = 2
thread 'main' panicked at 'attempt to subtract with overflow', /home/rbran/src/icicle-emu/icicle-vm/src/lib.rs:575:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:111:5
   3: icicle_vm::Vm::jit_exit_before_end_of_block
             at /home/rbran/src/icicle-emu/icicle-vm/src/lib.rs:575:9
   4: icicle_vm::Vm::run_block_jit
             at /home/rbran/src/icicle-emu/icicle-vm/src/lib.rs:555:13
   5: icicle_vm::Vm::run
             at /home/rbran/src/icicle-emu/icicle-vm/src/lib.rs:209:17
   6: icicle_vm::Vm::step
             at /home/rbran/src/icicle-emu/icicle-vm/src/lib.rs:917:20
   7: popsicle::main
             at ./src/main.rs:34:20
   8: core::ops::function::FnOnce::call_once
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

It seems to fail to stop executing after the 2 steps and try to execute invalid data after that? Also the addr on the hook trigger seems strange.

**Comment by mchesser** [comment] 2023-03-28 00:51
Dumping the pcode associated with the executed block it makes it slightly clearer what is going on:

```
    <L0> (entry=0x8000):
        hook.0()
[0x8000] mov r0,#0x1
        r0 = 0x1:4
        hook.1()
[0x8004] mov r1,#0x2
        r1 = 0x2:4
        invalid_instruction

```

If the instruction sequence ends in an invalid instruction (this appears is another issue), the JIT does not execute the usual block exit code (which clears the block offset) and instead triggers an exception. However, this exception occurs after the fuel is updated, causing the fuel decrementing code to be triggered twice. This has now been fixed.

We can also see why the hooks have the wrong offset, they are getting injected before the "marker" operation that updates the current instruction address. This is now fixed.

The final issue is why "invalid_instruction" is appearing in the first place. This is due to a flaw in the way `sleigh-runtime` matches constructors (see: #7). I implemented it this way because none of the specifications I initially tested with needed backtracking, and it slightly improves decoding performance by skipping it. Unfortunately, this causes issues with the ARM spec, so you need to use my patched version (https://github.com/icicle-emu/ghidra) at the moment, which resolves the issue by adjusting the location of some of the constraints: (https://github.com/icicle-emu/ghidra/commit/74023e97527954d44f7c4d40b06549a6858acdf3)

**Closed** 2023-03-28 00:50 UTC
